apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: auth-ingress
spec:
  tls:
    - hosts:
      - fake
      secretName: auth-tls-secret
  rules:
  - host: auth.localtest.me
    http:
      paths:
      - backend:
          serviceName: keycloak
          servicePort: 80
